import type { ActionMap } from "./base.js";

const P = "/api/atlas/v2";

export const cloudBackupActions: ActionMap = {
  list_export_buckets:            { method: "GET",    path: `${P}/groups/{groupId}/backup/exportBuckets` },
  get_export_bucket:              { method: "GET",    path: `${P}/groups/{groupId}/backup/exportBuckets/{exportBucketId}` },
  list_private_endpoints:         { method: "GET",    path: `${P}/groups/{groupId}/backup/{cloudProvider}/privateEndpoints` },
  get_private_endpoint:           { method: "GET",    path: `${P}/groups/{groupId}/backup/{cloudProvider}/privateEndpoints/{endpointId}` },
  get_compliance_policy:          { method: "GET",    path: `${P}/groups/{groupId}/backupCompliancePolicy` },
  list_exports:                   { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/exports` },
  get_export:                     { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/exports/{exportId}` },
  list_restore_jobs:              { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/restoreJobs` },
  get_restore_job:                { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/restoreJobs/{restoreJobId}` },
  get_schedule:                   { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/schedule` },
  list_snapshots:                 { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/snapshots` },
  get_snapshot:                   { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/snapshots/{snapshotId}` },
  list_sharded_snapshots:         { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/snapshots/shardedClusters` },
  get_sharded_snapshot:           { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/snapshots/shardedCluster/{snapshotId}` },
  list_serverless_restore_jobs:   { method: "GET",    path: `${P}/groups/{groupId}/serverless/{clusterName}/backup/restoreJobs` },
  get_serverless_restore_job:     { method: "GET",    path: `${P}/groups/{groupId}/serverless/{clusterName}/backup/restoreJobs/{restoreJobId}` },
  list_serverless_snapshots:      { method: "GET",    path: `${P}/groups/{groupId}/serverless/{clusterName}/backup/snapshots` },
  get_serverless_snapshot:        { method: "GET",    path: `${P}/groups/{groupId}/serverless/{clusterName}/backup/snapshots/{snapshotId}` },
  create_export_bucket:           { method: "POST",   path: `${P}/groups/{groupId}/backup/exportBuckets`, hasBody: true },
  create_private_endpoint:        { method: "POST",   path: `${P}/groups/{groupId}/backup/{cloudProvider}/privateEndpoints`, hasBody: true },
  create_export:                  { method: "POST",   path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/exports`, hasBody: true },
  create_restore_job:             { method: "POST",   path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/restoreJobs`, hasBody: true },
  take_snapshot:                  { method: "POST",   path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/snapshots`, hasBody: true },
  create_serverless_restore:      { method: "POST",   path: `${P}/groups/{groupId}/serverless/{clusterName}/backup/restoreJobs`, hasBody: true },
  update_compliance_policy:       { method: "PUT",    path: `${P}/groups/{groupId}/backupCompliancePolicy`, hasBody: true },
  update_export_bucket:           { method: "PATCH",  path: `${P}/groups/{groupId}/backup/exportBuckets/{exportBucketId}`, hasBody: true },
  update_schedule:                { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/schedule`, hasBody: true },
  update_snapshot:                { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/snapshots/{snapshotId}`, hasBody: true },
  delete_export_bucket:           { method: "DELETE", path: `${P}/groups/{groupId}/backup/exportBuckets/{exportBucketId}` },
  delete_private_endpoint:        { method: "DELETE", path: `${P}/groups/{groupId}/backup/{cloudProvider}/privateEndpoints/{endpointId}` },
  disable_compliance_policy:      { method: "DELETE", path: `${P}/groups/{groupId}/backupCompliancePolicy` },
  cancel_restore_job:             { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/restoreJobs/{restoreJobId}` },
  delete_schedule:                { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/schedule` },
  delete_sharded_snapshot:        { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/snapshots/shardedCluster/{snapshotId}` },
  delete_snapshot:                { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/snapshots/{snapshotId}` },
};

export const sharedTierBackupActions: ActionMap = {
  list_shared_snapshots:    { method: "GET",  path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/tenant/snapshots` },
  get_shared_snapshot:      { method: "GET",  path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/tenant/snapshots/{snapshotId}` },
  download_shared:          { method: "POST", path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/tenant/download`, hasBody: true },
  list_shared_restore_jobs: { method: "GET",  path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/tenant/restores` },
  get_shared_restore_job:   { method: "GET",  path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/tenant/restores/{restoreId}` },
  create_shared_restore:    { method: "POST", path: `${P}/groups/{groupId}/clusters/{clusterName}/backup/tenant/restore`, hasBody: true },
  list_flex_snapshots:      { method: "GET",  path: `${P}/groups/{groupId}/flexClusters/{name}/backup/snapshots` },
  get_flex_snapshot:        { method: "GET",  path: `${P}/groups/{groupId}/flexClusters/{name}/backup/snapshots/{snapshotId}` },
  download_flex:            { method: "POST", path: `${P}/groups/{groupId}/flexClusters/{name}/backup/download`, hasBody: true },
  list_flex_restore_jobs:   { method: "GET",  path: `${P}/groups/{groupId}/flexClusters/{name}/backup/restoreJobs` },
  get_flex_restore_job:     { method: "GET",  path: `${P}/groups/{groupId}/flexClusters/{name}/backup/restoreJobs/{restoreJobId}` },
  create_flex_restore:      { method: "POST", path: `${P}/groups/{groupId}/flexClusters/{name}/backup/restoreJobs`, hasBody: true },
};

export const legacyBackupActions: ActionMap = {
  list_checkpoints:   { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backupCheckpoints` },
  get_checkpoint:     { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/backupCheckpoints/{checkpointId}` },
  list_restore_jobs:  { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/restoreJobs` },
  get_restore_job:    { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/restoreJobs/{jobId}` },
  get_schedule:       { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/snapshotSchedule` },
  list_snapshots:     { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/snapshots` },
  get_snapshot:       { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/snapshots/{snapshotId}` },
  create_restore_job: { method: "POST",   path: `${P}/groups/{groupId}/clusters/{clusterName}/restoreJobs`, hasBody: true },
  update_schedule:    { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/snapshotSchedule`, hasBody: true },
  update_snapshot:    { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/snapshots/{snapshotId}`, hasBody: true },
  delete_snapshot:    { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/snapshots/{snapshotId}` },
};
