import type { ActionMap } from "./base.js";

const P = "/api/atlas/v2";

export const organizationActions: ActionMap = {
  list:               { method: "GET",    path: `${P}/orgs` },
  get:                { method: "GET",    path: `${P}/orgs/{orgId}` },
  get_projects:       { method: "GET",    path: `${P}/orgs/{orgId}/groups` },
  get_settings:       { method: "GET",    path: `${P}/orgs/{orgId}/settings` },
  list_invites:       { method: "GET",    path: `${P}/orgs/{orgId}/invites` },
  get_invite:         { method: "GET",    path: `${P}/orgs/{orgId}/invites/{invitationId}` },
  create:             { method: "POST",   path: `${P}/orgs`, hasBody: true },
  invite_user:        { method: "POST",   path: `${P}/orgs/{orgId}/invites`, hasBody: true },
  update:             { method: "PATCH",  path: `${P}/orgs/{orgId}`, hasBody: true },
  update_settings:    { method: "PATCH",  path: `${P}/orgs/{orgId}/settings`, hasBody: true },
  update_invite:      { method: "PATCH",  path: `${P}/orgs/{orgId}/invites/{invitationId}`, hasBody: true },
  update_invites:     { method: "PATCH",  path: `${P}/orgs/{orgId}/invites`, hasBody: true },
  update_user_roles:  { method: "PUT",    path: `${P}/orgs/{orgId}/users/{userId}/roles`, hasBody: true },
  delete:             { method: "DELETE", path: `${P}/orgs/{orgId}` },
  delete_invite:      { method: "DELETE", path: `${P}/orgs/{orgId}/invites/{invitationId}` },
};

export const projectActions: ActionMap = {
  list:                { method: "GET",    path: `${P}/groups` },
  get:                 { method: "GET",    path: `${P}/groups/{groupId}` },
  get_by_name:         { method: "GET",    path: `${P}/groups/byName/{groupName}` },
  get_ip_addresses:    { method: "GET",    path: `${P}/groups/{groupId}/ipAddresses` },
  get_settings:        { method: "GET",    path: `${P}/groups/{groupId}/settings` },
  list_limits:         { method: "GET",    path: `${P}/groups/{groupId}/limits` },
  get_limit:           { method: "GET",    path: `${P}/groups/{groupId}/limits/{limitName}` },
  get_mongodb_versions:{ method: "GET",    path: `${P}/groups/{groupId}/mongoDBVersions` },
  list_invites:        { method: "GET",    path: `${P}/groups/{groupId}/invites` },
  get_invite:          { method: "GET",    path: `${P}/groups/{groupId}/invites/{invitationId}` },
  create:              { method: "POST",   path: `${P}/groups`, hasBody: true },
  add_user:            { method: "POST",   path: `${P}/groups/{groupId}/access`, hasBody: true },
  invite_user:         { method: "POST",   path: `${P}/groups/{groupId}/invites`, hasBody: true },
  migrate:             { method: "POST",   path: `${P}/groups/{groupId}:migrate`, hasBody: true },
  update:              { method: "PATCH",  path: `${P}/groups/{groupId}`, hasBody: true },
  update_settings:     { method: "PATCH",  path: `${P}/groups/{groupId}/settings`, hasBody: true },
  set_limit:           { method: "PATCH",  path: `${P}/groups/{groupId}/limits/{limitName}`, hasBody: true },
  update_invite:       { method: "PATCH",  path: `${P}/groups/{groupId}/invites/{invitationId}`, hasBody: true },
  update_invites:      { method: "PATCH",  path: `${P}/groups/{groupId}/invites`, hasBody: true },
  update_user_roles:   { method: "PUT",    path: `${P}/groups/{groupId}/users/{userId}/roles`, hasBody: true },
  delete:              { method: "DELETE", path: `${P}/groups/{groupId}` },
  delete_invite:       { method: "DELETE", path: `${P}/groups/{groupId}/invites/{invitationId}` },
  delete_limit:        { method: "DELETE", path: `${P}/groups/{groupId}/limits/{limitName}` },
};

export const teamActions: ActionMap = {
  list_in_project:      { method: "GET",    path: `${P}/groups/{groupId}/teams` },
  get_in_project:       { method: "GET",    path: `${P}/groups/{groupId}/teams/{teamId}` },
  list_in_org:          { method: "GET",    path: `${P}/orgs/{orgId}/teams` },
  get_in_org:           { method: "GET",    path: `${P}/orgs/{orgId}/teams/{teamId}` },
  get_by_name:          { method: "GET",    path: `${P}/orgs/{orgId}/teams/byName/{teamName}` },
  add_to_project:       { method: "POST",   path: `${P}/groups/{groupId}/teams`, hasBody: true },
  create:               { method: "POST",   path: `${P}/orgs/{orgId}/teams`, hasBody: true },
  add_users:            { method: "POST",   path: `${P}/orgs/{orgId}/teams/{teamId}/users`, hasBody: true },
  add_user:             { method: "POST",   path: `${P}/orgs/{orgId}/teams/{teamId}:addUser`, hasBody: true },
  update_in_project:    { method: "PATCH",  path: `${P}/groups/{groupId}/teams/{teamId}`, hasBody: true },
  rename:               { method: "PATCH",  path: `${P}/orgs/{orgId}/teams/{teamId}`, hasBody: true },
  remove_from_project:  { method: "DELETE", path: `${P}/groups/{groupId}/teams/{teamId}` },
  delete:               { method: "DELETE", path: `${P}/orgs/{orgId}/teams/{teamId}` },
  remove_user:          { method: "DELETE", path: `${P}/orgs/{orgId}/teams/{teamId}/users/{userId}` },
};

export const apiKeyActions: ActionMap = {
  list_in_project:          { method: "GET",    path: `${P}/groups/{groupId}/apiKeys` },
  list_in_org:              { method: "GET",    path: `${P}/orgs/{orgId}/apiKeys` },
  get:                      { method: "GET",    path: `${P}/orgs/{orgId}/apiKeys/{apiUserId}` },
  list_access_list:         { method: "GET",    path: `${P}/orgs/{orgId}/apiKeys/{apiUserId}/accessList` },
  get_access_list_entry:    { method: "GET",    path: `${P}/orgs/{orgId}/apiKeys/{apiUserId}/accessList/{ipAddress}` },
  create_in_project:        { method: "POST",   path: `${P}/groups/{groupId}/apiKeys`, hasBody: true },
  assign_to_project:        { method: "POST",   path: `${P}/groups/{groupId}/apiKeys/{apiUserId}`, hasBody: true },
  create_in_org:            { method: "POST",   path: `${P}/orgs/{orgId}/apiKeys`, hasBody: true },
  add_access_list_entry:    { method: "POST",   path: `${P}/orgs/{orgId}/apiKeys/{apiUserId}/accessList`, hasBody: true },
  update_in_project:        { method: "PATCH",  path: `${P}/groups/{groupId}/apiKeys/{apiUserId}`, hasBody: true },
  update_in_org:            { method: "PATCH",  path: `${P}/orgs/{orgId}/apiKeys/{apiUserId}`, hasBody: true },
  remove_from_project:      { method: "DELETE", path: `${P}/groups/{groupId}/apiKeys/{apiUserId}` },
  delete:                   { method: "DELETE", path: `${P}/orgs/{orgId}/apiKeys/{apiUserId}` },
  delete_access_list_entry: { method: "DELETE", path: `${P}/orgs/{orgId}/apiKeys/{apiUserId}/accessList/{ipAddress}` },
};

export const serviceAccountActions: ActionMap = {
  list_in_project:                  { method: "GET",    path: `${P}/groups/{groupId}/serviceAccounts` },
  get_in_project:                   { method: "GET",    path: `${P}/groups/{groupId}/serviceAccounts/{clientId}` },
  list_access_list_in_project:      { method: "GET",    path: `${P}/groups/{groupId}/serviceAccounts/{clientId}/accessList` },
  list_in_org:                      { method: "GET",    path: `${P}/orgs/{orgId}/serviceAccounts` },
  get_in_org:                       { method: "GET",    path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}` },
  list_access_list_in_org:          { method: "GET",    path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}/accessList` },
  get_groups:                       { method: "GET",    path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}/groups` },
  create_in_project:                { method: "POST",   path: `${P}/groups/{groupId}/serviceAccounts`, hasBody: true },
  add_access_list_in_project:       { method: "POST",   path: `${P}/groups/{groupId}/serviceAccounts/{clientId}/accessList`, hasBody: true },
  create_secret_in_project:         { method: "POST",   path: `${P}/groups/{groupId}/serviceAccounts/{clientId}/secrets`, hasBody: true },
  invite_to_project:                { method: "POST",   path: `${P}/groups/{groupId}/serviceAccounts/{clientId}:invite`, hasBody: true },
  create_in_org:                    { method: "POST",   path: `${P}/orgs/{orgId}/serviceAccounts`, hasBody: true },
  add_access_list_in_org:           { method: "POST",   path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}/accessList`, hasBody: true },
  create_secret_in_org:             { method: "POST",   path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}/secrets`, hasBody: true },
  update_in_project:                { method: "PATCH",  path: `${P}/groups/{groupId}/serviceAccounts/{clientId}`, hasBody: true },
  update_in_org:                    { method: "PATCH",  path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}`, hasBody: true },
  delete_from_project:              { method: "DELETE", path: `${P}/groups/{groupId}/serviceAccounts/{clientId}` },
  delete_access_list_in_project:    { method: "DELETE", path: `${P}/groups/{groupId}/serviceAccounts/{clientId}/accessList/{ipAddress}` },
  delete_secret_in_project:         { method: "DELETE", path: `${P}/groups/{groupId}/serviceAccounts/{clientId}/secrets/{secretId}` },
  delete_from_org:                  { method: "DELETE", path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}` },
  delete_access_list_in_org:        { method: "DELETE", path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}/accessList/{ipAddress}` },
  delete_secret_in_org:             { method: "DELETE", path: `${P}/orgs/{orgId}/serviceAccounts/{clientId}/secrets/{secretId}` },
};

export const cloudUserActions: ActionMap = {
  list_in_project:      { method: "GET",    path: `${P}/groups/{groupId}/users` },
  get_in_project:       { method: "GET",    path: `${P}/groups/{groupId}/users/{userId}` },
  list_in_org:          { method: "GET",    path: `${P}/orgs/{orgId}/users` },
  get_in_org:           { method: "GET",    path: `${P}/orgs/{orgId}/users/{userId}` },
  list_in_team:         { method: "GET",    path: `${P}/orgs/{orgId}/teams/{teamId}/users` },
  get_by_name:          { method: "GET",    path: `${P}/users/byName/{userName}` },
  get:                  { method: "GET",    path: `${P}/users/{userId}` },
  add_to_project:       { method: "POST",   path: `${P}/groups/{groupId}/users`, hasBody: true },
  add_project_role:     { method: "POST",   path: `${P}/groups/{groupId}/users/{userId}:addRole`, hasBody: true },
  remove_project_role:  { method: "POST",   path: `${P}/groups/{groupId}/users/{userId}:removeRole`, hasBody: true },
  add_to_team:          { method: "POST",   path: `${P}/orgs/{orgId}/teams/{teamId}/users`, hasBody: true },
  remove_from_team:     { method: "POST",   path: `${P}/orgs/{orgId}/teams/{teamId}:removeUser`, hasBody: true },
  create_in_org:        { method: "POST",   path: `${P}/orgs/{orgId}/users`, hasBody: true },
  add_org_role:         { method: "POST",   path: `${P}/orgs/{orgId}/users/{userId}:addRole`, hasBody: true },
  remove_org_role:      { method: "POST",   path: `${P}/orgs/{orgId}/users/{userId}:removeRole`, hasBody: true },
  create:               { method: "POST",   path: `${P}/users`, hasBody: true },
  update_in_org:        { method: "PATCH",  path: `${P}/orgs/{orgId}/users/{userId}`, hasBody: true },
  remove_from_project:  { method: "DELETE", path: `${P}/groups/{groupId}/users/{userId}` },
  remove_from_org:      { method: "DELETE", path: `${P}/orgs/{orgId}/users/{userId}` },
};
