import type { ActionMap } from "./base.js";

const P = "/api/atlas/v2";

export const atlasSearchActions: ActionMap = {
  list_indexes_legacy: { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/fts/indexes/{databaseName}/{collectionName}` },
  get_index_legacy:    { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/fts/indexes/{indexId}` },
  get_deployment:      { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/search/deployment` },
  list_indexes:        { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes` },
  list_by_type:        { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes/{databaseName}/{collectionName}` },
  get_by_name:         { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes/{databaseName}/{collectionName}/{indexName}` },
  get:                 { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes/{indexId}` },
  create_legacy:       { method: "POST",   path: `${P}/groups/{groupId}/clusters/{clusterName}/fts/indexes`, hasBody: true },
  create_deployment:   { method: "POST",   path: `${P}/groups/{groupId}/clusters/{clusterName}/search/deployment`, hasBody: true },
  create:              { method: "POST",   path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes`, hasBody: true },
  update_legacy:       { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/fts/indexes/{indexId}`, hasBody: true },
  update_deployment:   { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/search/deployment`, hasBody: true },
  update_by_name:      { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes/{databaseName}/{collectionName}/{indexName}`, hasBody: true },
  update:              { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes/{indexId}`, hasBody: true },
  delete_legacy:       { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/fts/indexes/{indexId}` },
  delete_deployment:   { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/search/deployment` },
  delete_by_name:      { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes/{databaseName}/{collectionName}/{indexName}` },
  delete:              { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/search/indexes/{indexId}` },
};

export const dataFederationActions: ActionMap = {
  list:                    { method: "GET",    path: `${P}/groups/{groupId}/dataFederation` },
  get:                     { method: "GET",    path: `${P}/groups/{groupId}/dataFederation/{tenantName}` },
  list_limits:             { method: "GET",    path: `${P}/groups/{groupId}/dataFederation/{tenantName}/limits` },
  get_limit:               { method: "GET",    path: `${P}/groups/{groupId}/dataFederation/{tenantName}/limits/{limitName}` },
  download_query_logs:     { method: "GET",    path: `${P}/groups/{groupId}/dataFederation/{tenantName}/queryLogs.gz` },
  list_private_endpoints:  { method: "GET",    path: `${P}/groups/{groupId}/privateNetworkSettings/endpointIds` },
  get_private_endpoint:    { method: "GET",    path: `${P}/groups/{groupId}/privateNetworkSettings/endpointIds/{endpointId}` },
  create:                  { method: "POST",   path: `${P}/groups/{groupId}/dataFederation`, hasBody: true },
  create_private_endpoint: { method: "POST",   path: `${P}/groups/{groupId}/privateNetworkSettings/endpointIds`, hasBody: true },
  update:                  { method: "PATCH",  path: `${P}/groups/{groupId}/dataFederation/{tenantName}`, hasBody: true },
  set_limit:               { method: "PATCH",  path: `${P}/groups/{groupId}/dataFederation/{tenantName}/limits/{limitName}`, hasBody: true },
  delete:                  { method: "DELETE", path: `${P}/groups/{groupId}/dataFederation/{tenantName}` },
  delete_limit:            { method: "DELETE", path: `${P}/groups/{groupId}/dataFederation/{tenantName}/limits/{limitName}` },
  delete_private_endpoint: { method: "DELETE", path: `${P}/groups/{groupId}/privateNetworkSettings/endpointIds/{endpointId}` },
};

export const dataLakePipelineActions: ActionMap = {
  list:           { method: "GET",    path: `${P}/groups/{groupId}/pipelines` },
  get:            { method: "GET",    path: `${P}/groups/{groupId}/pipelines/{pipelineName}` },
  get_schedules:  { method: "GET",    path: `${P}/groups/{groupId}/pipelines/{pipelineName}/availableSchedules` },
  get_snapshots:  { method: "GET",    path: `${P}/groups/{groupId}/pipelines/{pipelineName}/availableSnapshots` },
  list_runs:      { method: "GET",    path: `${P}/groups/{groupId}/pipelines/{pipelineName}/runs` },
  get_run:        { method: "GET",    path: `${P}/groups/{groupId}/pipelines/{pipelineName}/runs/{pipelineRunId}` },
  create:         { method: "POST",   path: `${P}/groups/{groupId}/pipelines`, hasBody: true },
  pause:          { method: "POST",   path: `${P}/groups/{groupId}/pipelines/{pipelineName}/pause` },
  resume:         { method: "POST",   path: `${P}/groups/{groupId}/pipelines/{pipelineName}/resume` },
  trigger:        { method: "POST",   path: `${P}/groups/{groupId}/pipelines/{pipelineName}/trigger`, hasBody: true },
  update:         { method: "PATCH",  path: `${P}/groups/{groupId}/pipelines/{pipelineName}`, hasBody: true },
  delete:         { method: "DELETE", path: `${P}/groups/{groupId}/pipelines/{pipelineName}` },
  delete_run:     { method: "DELETE", path: `${P}/groups/{groupId}/pipelines/{pipelineName}/runs/{pipelineRunId}` },
};

export const onlineArchiveActions: ActionMap = {
  list:                { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/onlineArchives` },
  download_query_logs: { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/onlineArchives/queryLogs.gz` },
  get:                 { method: "GET",    path: `${P}/groups/{groupId}/clusters/{clusterName}/onlineArchives/{archiveId}` },
  create:              { method: "POST",   path: `${P}/groups/{groupId}/clusters/{clusterName}/onlineArchives`, hasBody: true },
  update:              { method: "PATCH",  path: `${P}/groups/{groupId}/clusters/{clusterName}/onlineArchives/{archiveId}`, hasBody: true },
  delete:              { method: "DELETE", path: `${P}/groups/{groupId}/clusters/{clusterName}/onlineArchives/{archiveId}` },
};

export const streamActions: ActionMap = {
  list_workspaces:        { method: "GET",    path: `${P}/groups/{groupId}/streams` },
  get_account:            { method: "GET",    path: `${P}/groups/{groupId}/streams/accountDetails` },
  list_active_vpc_peering:{ method: "GET",    path: `${P}/groups/{groupId}/streams/activeVpcPeeringConnections` },
  list_privatelink:       { method: "GET",    path: `${P}/groups/{groupId}/streams/privateLinkConnections` },
  get_privatelink:        { method: "GET",    path: `${P}/groups/{groupId}/streams/privateLinkConnections/{connectionId}` },
  list_vpc_peering:       { method: "GET",    path: `${P}/groups/{groupId}/streams/vpcPeeringConnections` },
  get_workspace:          { method: "GET",    path: `${P}/groups/{groupId}/streams/{tenantName}` },
  download_audit_logs:    { method: "GET",    path: `${P}/groups/{groupId}/streams/{tenantName}/auditLogs` },
  list_connections:       { method: "GET",    path: `${P}/groups/{groupId}/streams/{tenantName}/connections` },
  get_connection:         { method: "GET",    path: `${P}/groups/{groupId}/streams/{tenantName}/connections/{connectionName}` },
  get_processor:          { method: "GET",    path: `${P}/groups/{groupId}/streams/{tenantName}/processor/{processorName}` },
  list_processors:        { method: "GET",    path: `${P}/groups/{groupId}/streams/{tenantName}/processors` },
  create_workspace:       { method: "POST",   path: `${P}/groups/{groupId}/streams`, hasBody: true },
  create_privatelink:     { method: "POST",   path: `${P}/groups/{groupId}/streams/privateLinkConnections`, hasBody: true },
  accept_vpc_peering:     { method: "POST",   path: `${P}/groups/{groupId}/streams/vpcPeeringConnections/{id}:accept`, hasBody: true },
  reject_vpc_peering:     { method: "POST",   path: `${P}/groups/{groupId}/streams/vpcPeeringConnections/{id}:reject` },
  create_connection:      { method: "POST",   path: `${P}/groups/{groupId}/streams/{tenantName}/connections`, hasBody: true },
  create_processor:       { method: "POST",   path: `${P}/groups/{groupId}/streams/{tenantName}/processor`, hasBody: true },
  start_processor:        { method: "POST",   path: `${P}/groups/{groupId}/streams/{tenantName}/processor/{processorName}:start` },
  start_processor_with:   { method: "POST",   path: `${P}/groups/{groupId}/streams/{tenantName}/processor/{processorName}:startWith`, hasBody: true },
  stop_processor:         { method: "POST",   path: `${P}/groups/{groupId}/streams/{tenantName}/processor/{processorName}:stop` },
  sample_connections:     { method: "POST",   path: `${P}/groups/{groupId}/streams:withSampleConnections`, hasBody: true },
  update_workspace:       { method: "PATCH",  path: `${P}/groups/{groupId}/streams/{tenantName}`, hasBody: true },
  update_connection:      { method: "PATCH",  path: `${P}/groups/{groupId}/streams/{tenantName}/connections/{connectionName}`, hasBody: true },
  update_processor:       { method: "PATCH",  path: `${P}/groups/{groupId}/streams/{tenantName}/processor/{processorName}`, hasBody: true },
  delete_privatelink:     { method: "DELETE", path: `${P}/groups/{groupId}/streams/privateLinkConnections/{connectionId}` },
  delete_vpc_peering:     { method: "DELETE", path: `${P}/groups/{groupId}/streams/vpcPeeringConnections/{id}` },
  delete_workspace:       { method: "DELETE", path: `${P}/groups/{groupId}/streams/{tenantName}` },
  delete_connection:      { method: "DELETE", path: `${P}/groups/{groupId}/streams/{tenantName}/connections/{connectionName}` },
  delete_processor:       { method: "DELETE", path: `${P}/groups/{groupId}/streams/{tenantName}/processor/{processorName}` },
};
